# Generated by Django 5.1.2 on 2025-01-02 23:08

import private_chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
        ('users_accounts', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=private_chat.models.user_directory_path, validators=[private_chat.models.validate_file_size], verbose_name='File'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['read'], name='private_cha_read_7497f3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['created'], name='private_cha_created_aa79a9_idx'),
        ),
    ]
