# Generated by Django 5.1.2 on 2025-01-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_messagemodel_dialog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='dialog',
        ),
    ]
