# Generated by Django 5.1.2 on 2024-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_accounts', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
