# Generated by Django 5.1.2 on 2025-01-03 00:33

import users_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_accounts', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(validators=[users_accounts.models.validate_birthdate]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=users_accounts.models.profile_image_path),
        ),
    ]
